### ISSUE TITLE
filter old build artifacts out of repo history

### ISSUE THREAD

**Issue by pospi** [lightningrodlabs/rea-playspace#139]
The repo is quite large to clone: 173.82 MiB @adaburrows and I think there are archival binaries that need to be filtered out of git history.

This will be simple to do, but disruptive & require all contributors to sync their updates.

**Comment by adaburrows** [comment]
I looked at this for a little while trying to figure out which binaries might be in the history. For a while, we used the inherited process from the original repo which had the the built DNA and happ checked in in order to speed up the testing and building process on github, but our new process that doesn't require that is actually faster. I'm betting there's a lot of builds from both our initial version of the app and from whichever project the template repo came from. Doing a [git-filter-repo](https://github.com/newren/git-filter-repo/) to remove everything in the `.gitignore` should go a long way towards cleaning it up. We can additionally add the `electron` directory that we deleted a while ago.

In the mean time, cloning with `--depth 1` will only fetch the last commit and should be sufficient for people wanting to use the project. I think we'll be able to get to this within the next few days.

**Comment by adaburrows** [comment]
Oh, we should also filter out `workdir/rea-playspace.webhapp`. I don't believe we use that file and it takes up about 14MB.

**Comment by adaburrows** [comment]
Aha! `git filter-repo` has an analysis feature. The analysis gave me a file I could parse into a list of files. We just need to get to a good point to sync on our work with the repo. Then bye-bye extra blobs.

I put the file I made over in `.git/filter-repo/analysis/deleted-paths.txt` in my copy of the repo.

**Comment by adaburrows** [comment]
`git filter-repo --invert-paths --paths-from-file .git/filter-repo/analysis/deleted-paths.txt`

**Comment by adaburrows** [comment]
Ok, new size is about 18 MiB:

```
Writing objects: 100% (4156/4156), 17.97 MiB | 517.00 KiB/s, done.
``
