### ISSUE TITLE
Bug?:  Blank canvas even though data seems to be there

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#171]
I'm trying to get back into what I did for the Simon's Rock demo, which ended up being launcher 0.6.0, playspace 0.0.15.  The network seed is simons-rock-5.

It has the left side, the resource specs and the process specs, but nothing on the canvas.  If I go to Events, the list of events is there.  If I go to Resources, there is nothing.

Possibly useful: Bob went into that same seed when I was not in holochain at all, and it came up with no data.  We thought that could be because I wasn't online and all the data is probably with me.  So I went in.  After that, he could also get the left side but not the canvas.

Mostly, I need to know what is going on so I can work with users and not have this kind of thing happen.  If I understand the parameters and what works in this condition, I can try to keep it working well enough.

**Comment by adaburrows** [comment]
> Possibly useful: Bob went into that same seed when I was not in holochain at all, and it came up with no data. We thought that could be because I wasn't online and all the data is probably with me. So I went in. After that, he could also get the left side but not the canvas.

Yes, this is a known issue. If someone else visits the app before the backend zome has finished synchronizing with the network, the frontend app will overwrite the info that tells the application which Plan to load.

This means that we need to officially start supporting multiple Plans in a more robust manner.

There is no easy way to get back to the correct plan, because we would need to change the zome and that will partition the network because it would be a breaking change. There is a possibility that we can add a menu option to switch to a particular plan, since we can have a list of all of them. However, it feels like that wouldn't be particularly productive. I would rather flesh out the UI that supports multiple plans.

**Comment by adaburrows** [comment]
See #172 for more information. I just wrote up the problem there. While it doesn't have all the explanation I initially wanted, it is very concise.
