### ISSUE TITLE
Bug: Don't allow operator to pick primary accountable

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#176]
![Screenshot from 2022-10-29 13-02-23](https://user-images.githubusercontent.com/3776081/198847750-0895ec74-9317-47d3-a683-15669a1e88dc.png)

The primaryAccountable is set to equal the receiver on the event that creates the resource.

**Comment by adaburrows** [comment]
It is still set by the event. This was just a general form I created for entering the EconomicResouce values.

*Should we ever allow setting the primary accountable field on an EconomicResource?** Probably not, especially since it just gets overwritten at the next stage of code execution.

We have two choices:
1. I can remove it from the form entirely.
2. I can disable it and set it equal to what it will be after the event is applied (so people can see that connection).

**Comment by fosterlynn** [comment]
>We have two choices:

Either one is fine.  Might be better to just remove it and keep the form simpler?

**Comment by adaburrows** [comment]
Aha, we now have a hypothesis. Let's keep it ask people if it provides any value.

**Comment by fosterlynn** [comment]
>Let's keep it and ask people if it provides any value.

Whatever you prefer.

**Comment by fosterlynn** [comment]
I'm thinking this one should go in the milestone?  (We can see what all is there vs what time there is....)
