### ISSUE TITLE
Bug: Resource not required in event

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#177]
![Screenshot from 2022-10-29 13-06-16](https://user-images.githubusercontent.com/3776081/198847787-07860501-9e70-496d-96ef-94b1d2eb8dc7.png)

The text says "One or both of the following need to be filled in", but actually neither needs to be filled in.

Some resources are not worth inventorying, it is the agent's choice.  By making this choice, it is not on their inventory or anywhere else as a resource.  See https://www.valueflo.ws/concepts/resources/#inventory.

**Comment by adaburrows** [comment]
I feel lost whenever I read this, mostly because things are not grouped according to how my mind processes the information and many of the logical case are written out. I have to use logic, since I'm programming it. I see a bunch of different cases created by the three scenarios:
1. Inventoried &mdash; There is a specific EconomicResource this quantity should be mapped onto.
2. Not-inventoried &mdash; Actually, this is an intriguing thing to think about, because really, you're saying there is only the concept of the object and the inventory can be lifted to the ResourceSpecification object through the values quantified in the events, but then if an event maps it to a specific EconomicResource, it once again has a separate Object as it's identity.
4. Not-sensibly-inventoried &mdash; Let's just go with work, services, and air we breathe.

So we have the following maps, which should lead to a system that is composable based off the series of Events applied (each event is essentially a mathematical function):
1. Inventoried -> Inventoried
2. Inventoried -> Not-inventoried
3. Not-inventoried -> Inventoried
4. Not-inventoried -> Not-inventoried

Are you specifically talking about the 4th case that the text doesn't allow for? In that case, yes, it doesn't make sense to keep the text that way. However, I would like to have logic that accounts for that scenario and does light validation, is there a possibility that the data model lets one understand that this was also not inventoried in the previous link?

For example, in the playspace, if we are going through map 2, Inventoried -> Not-inventoried, we need to have the object the provider uses or the accounting will be off. However, if we have map 4, Not-inventoried -> Not-inventoried, then we need neither, but we need to be sure it wasn't accounted for by the provider, otherwise the accounting will be off.

**Comment by fosterlynn** [comment]
> Are you specifically talking about the 4th case that the text doesn't allow for?

Yes.

>is there a possibility that the data model lets one understand that this was also not inventoried in the previous link?

For receiver resources, I doubt it, how do you know what "this" is earlier in the flow?  I think we have to trust the users in some cases to do what they want to do in their situation.  There might be some configurations that could help for situations where say agents inventory everything or nothing; or possibly can set a flag in their version of the resource spec, and if we add "their version of the resource spec", we could look at it again.  But for now, I think this is a very low priority, not even a backlog item.

In the case of the provider resource, we do actually know about that already if there is one, it was decided earlier and some day will be displayed on the canvas as an inventoried resource if it is one.  So that means it isn't needed in the form, see #180 .  Am I missing something?

Feel free to split things out as you wish in terms of issues.
