### ISSUE TITLE
Improvement: In event show only resources where the accountable fits

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#178]
![Screenshot from 2022-10-29 13-06-57](https://user-images.githubusercontent.com/3776081/198848449-5d2b004f-6ffc-4bd4-8824-1aa9dfff2a3b.png)

In the resource drop downs, it looks like all resources for the resource spec are shown.  If we can limit that further to only resources where the provider or receiver agent (depending on which dropdown) is the primaryAccountable, that will be less confusing.

This should at least be true for transfer, transferAllRights, produce, raise, move.  I need to try out and think about transferCustody, and possibly other actions, will come back and update this after that.

**Comment by adaburrows** [comment]
I agree. I was thinking about that at one point, but it slipped my mind and I didn't write it down.

I just looked through the code we have of the actions and their definitions, I think it should hold for everything except, `use`, `pickup`, `dropoff`, or `cite`, but here's the full list of things I think it might not apply to:
* One can `use` a tool or other resource that isn't theirs as long as they have access to it and permission to use it.
* One can `pickup` and `dropoff` something that is not, and never becomes their property or inventory.
* One can `cite` a book that belongs to a college, library, or a friend as long as they have access to it and permission to use it.
* The action `work` is never inventoried so it doesn't really apply.
* The actions `combine` and `separate` might have mixed ownership since a shipment might be packaged into a TEU (20 ft equivalent unit) and shipped overseas, but the combined items may still be owned by the originating Agent even though the TEU is owned by the shipping company. This also means that there might be a forgetful functor in the `combine` and `separate` effects unless that information could be made evident in a nested shipping manifest that allows recovering the ownership of each item (or the data needs to be recovered from the inverse of the operad that is formed by all the events in the graph leading up to the final combine event before it is separated).

**Comment by adaburrows** [comment]
Oh, and to simply explain the forgetful functor bit (and the operad while I'm at it):
1. Let's take a look at the expression 4x^2 + 2y + 3 = z, and call it operad A.
2. A forms an operad with three inputs to an addition operator and one output (think of this as analogous to combining).
3. If we set the values of `x` and `y` to a real value, we can evaluate the whole operad. For instance, `x=2` and `y=3`, then `z=25`.
4. We may also define a functor that maps the operad to the set of real numbers. In doing this, we discard the whole structure of how it was created, but we know that the functor maps A(2,3) -> R. This is a forgetful because all we are left with is that A(2,3) equals 25, but we have no idea how it came to be that.
5. We could have a faithful functor that maps it from the category of operads to the category of graphs, then every operation would be preserved in the graph structure.

I will note that since `combine` and `separate` are reciprocal actions, it would seem that we would need to follow the inverse of the original operad that formed it, but I think that neess to be made clear in the spec.

**Comment by fosterlynn** [comment]
Or, we can look at what actually happens in real life and in the data model.  When a resource is combined into another resource, it still exists as a resource with all its data intact, including its identifier and its primaryAccountable.  There isn't any issue of forgetting something, or having to put things back in place when it is separated or while it is combined.  Combined resources can be reported on easily.

>the combined items may still be owned by the originating Agent even though the TEU is owned by the shipping company

Exactly.  In fact most often the shipping agent does not own what is being shipped inside their container or truck or package or whatever, although they do of course have a number of responsibilities for those items.  Usually shipped items are owned by the agent it is shipped from or the agent it is shipped to.  Contract will determine when the ownership changes.  Being contained would limit what other actions can be done to a resource.

**Comment by adaburrows** [comment]
I think we are saying the same thing, I'm just using more math. I also forgot that `containedIn` was a field on the original resource.

**Comment by adaburrows** [comment]
To be clear, `containedIn` provides the manifest and the mathematical map needed to not be a forgetful functor (my brain is the forgetful functor here).

**Comment by fosterlynn** [comment]
>I just looked through the code we have of the actions and their definitions, I think it should hold for everything except, use, pickup, dropoff, or cite

Hmmmm.  Are we really only talking about the actions that are in the changeResource column [here](https://www.valueflo.ws/assets/vf-actions.png)?  

transferCustody is a bit weird.  And the table might be wrong in some cases too, hasn't really been tested in actual use cases, at least the new properties like changeResource.

**Comment by adaburrows** [comment]
> Hmmmm. Are we really only talking about the actions that are in the changeResource column [here](https://www.valueflo.ws/assets/vf-actions.png)?

No, I paid no attention to that. 🙃

**Comment by adaburrows** [comment]
> changeResource column [here](https://www.valueflo.ws/assets/vf-actions.png)?

Wait, which column were you actually referring to? Has it been long enough that column isn't there anymore, or was `changeResource` an error?

**Comment by adaburrows** [comment]
Oh well, it probably doesn't matter to much. I'll just restrain it on everything and if that's to restrictive, we can add more logic later.
