### ISSUE TITLE
Bug: To state or not to state, that is the question :)

### ISSUE THREAD

**Issue by fosterlynn** [lightningrodlabs/rea-playspace#179]
Right now, it looks like you are displaying state on the resource.  But there is no way to actually create the state.  If we want to support that in the playspace, we need to allow entry of state on the event.  (This does not apply to stage, which can be derived from existing data.)

**Comment by adaburrows** [comment]
This is correct. I was wanting to make sure our accounting logic was solid before extending the form fields to include state. It seems to be because I implemented it during the accounting sprint. However, we need a task to wire up the state field.

The big question:
* What are the allowable values for this, or do we allow anything?

**Comment by fosterlynn** [comment]
>What are the allowable values for this, or do we allow anything?

Any string.

**Comment by adaburrows** [comment]
We have decided not to state for now.
