### ISSUE TITLE
Bug: Label code crashes with resourceQuantity & effortQuantity

### ISSUE THREAD

**Issue by adaburrows** [lightningrodlabs/rea-playspace#63]
Currently, the code that generates the edge labels assumes there will only be one of resourceQuantity xor effortQuantity.

What should this label like? Something like: "Jill: Use 1 table saw for 1 hr."

Also, what are the validation rules for this. Is it an edge case for the "use" action, or can other actions use it too?

**Comment by fosterlynn** [comment]
>What should this label like? Something like: "Jill: Use 1 table saw for 1 hr."

A couple things about this.  One to note is that the provider will be the agent who is providing the saw to the process (the primaryAccountable probably), not necessarily the one using it in the process.  Or several people could use the same equipment.  So it really isn't in the data model the way I read this label example. But maybe it is still OK as is, the context should be pretty clear, and it is easier to treat all flows the same. 

But more importantly, I'm wondering if we want to simplify this.  Having both a resourceQuantity and an effortQuantity on flows is there for completeness in VF, after many(!) hours of discussion.  It only applies to `use` for what we are doing here.  And resourceQuantity would only be used if >1, we wouldn't want to require it imo. And I think it will be pretty unlikely in almost all use cases, although I could see they might schedule 3 hoes for three people doing weeding, so it could happen.  But there is a big trade-off with clarity and simplicity for users.  I've already started entering the first one when I want the other every time, and also they require some explanation.

My opinion atm is that we should display only 1 quantity on the modal, and if the action is `work` or `use` then save it as effortQuantity, else save it as resourceQuantity.    In other words going for simplicity for users.  I could be wrong.  But if we have both, I think it would be worth some thought on how to make the UX more clear.

If we decide to simplify, the label would be something like:  "Garden Class: Use table saw for 1 hr." or for work "Jill: Work building for 1 hr."  (Not sure how you are formatting the other actions.  They might have to be different, like "Garden Class: Consume 5 gal compost.")

P.S. If this should be a different issue, I'll move it.  But it is pretty related.

**Comment by fosterlynn** [comment]
In the meeting today, I think we tentatively decided to just show one quantity, and have the code save it to the right property based on action: `use` or `work` go to `effortQuantity`, everything else goes to `resourceQuantity`.  If anyone disagrees, or we want to rethink, we can do that.  At some point, we can think about how to also allow a `resourceQuantity` in case of `use` without confusing the UX too much.

Note: If we do this, we don't have to worry about having a blank unit in the list or another way to  clear unit, because it will be required.

**Comment by adaburrows** [comment]
The easiest thing is to leave everything there and editable. I just wanted to know how the labels should be written out for use.

Sounds like it will be like: "Sonia: Use 3 of Jill's Ladders for 2 hours."

**Comment by fosterlynn** [comment]
>"Sonia: Use 3 of Jill's Ladders for 2 hours."

There aren't places for 2 agents as in this.  Since they are Jill's ladders, Jill is the provider.  We don't have the work events connected to the equipment/tools used events directly, just generally through the process, so if there are more than one worker, we don't know who used what.

Whatever you do today is fine.  If you want, tomorrow I can do some work on how to format those labels across actions, see what all the variations might be and think about how to best consolidate them.  This won't be the only action where "Name: action...." won't make the most sense.  But it's fine for now.

>The easiest thing is to leave everything there and editable.

Yes, if we want to support both for `use`, then I am off topic.  I'll start another issue for the UX, and assign it to me.  Wouldn't have to be done right away.

**Comment by adaburrows** [comment]
https://github.com/lightningrodlabs/rea-playspace/issues/72
